
import playerDataSlice from "./slices/playerDataSlice";
import hoverSlice from "./slices/hoverSlice";
import homeSlice from "./slices/homeSlice";
import collectionSlice from "./slices/collectionSlice";
import exploreSlice from "./slices/exploreSlice";
import matchesSlice from "./slices/matchesSlice";
import eventsSlice from "./slices/eventsSlice";
import decksSlice from "./slices/decksSlice";
import economySlice from "./slices/economySlice";
import draftsSlice from "./slices/draftsSlice";
import seasonalSlice from "./slices/seasonalSlice";
import deckChangesSlice from "./slices/deckChangesSlice";

const actions: Record<string, (arg: any) => any> = {};
actions["SET_HOVER_IN"] = hoverSlice.actions.setHoverIn;
actions["SET_HOVER_OUT"] = hoverSlice.actions.setHoverOut;
actions["SET_HOME_DATA"] = homeSlice.actions.setHomeData;
actions["SET_BOOSTER_WIN_FACTOR"] = collectionSlice.actions.setBoosterWinFactor;
actions["SET_COUNT_MODE"] = collectionSlice.actions.setCountMode;
actions["SET_FUTURE_BOOSTERS"] = collectionSlice.actions.setFutureBoosters;
actions["SET_MYTHIC_DRAFT_FACTOR"] =
  collectionSlice.actions.setMythicDraftFactor;
actions["SET_RARE_DRAFT_FACTOR"] = collectionSlice.actions.setRareDraftFactor;
actions["SET_ACTIVE_EVENTS"] = exploreSlice.actions.setActiveEvents;
actions["SET_EXPLORE_DATA"] = exploreSlice.actions.setExploreData;
actions["SET_EXPLORE_FILTERS"] = exploreSlice.actions.setExploreFilters;
actions["SET_EXPLORE_FILTERS_SKIP"] =
  exploreSlice.actions.setExploreFiltersSkip;
actions["SET_MATCH"] = matchesSlice.actions.setMatch;
actions["SET_MANY_MATCHES"] = matchesSlice.actions.setManyMatches;
actions["SET_EVENT"] = eventsSlice.actions.setEvent;
actions["SET_MANY_EVENTS"] = eventsSlice.actions.setManyEvents;
actions["SET_PLAYERDB"] = playerDataSlice.actions.setPlayerDb;
actions["SET_APPDB"] = playerDataSlice.actions.setAppDb;
actions["SET_PLAYER_ID"] = playerDataSlice.actions.setPlayerId;
actions["SET_PLAYER_NAME"] = playerDataSlice.actions.setPlayerName;
actions["SET_ARENA_VERSION"] = playerDataSlice.actions.setArenaVersion;
actions["SET_PLAYER_ECONOMY"] = playerDataSlice.actions.setEconomy;
actions["SET_TAG_COLORS"] = playerDataSlice.actions.setTagColors;
actions["EDIT_TAG_COLOR"] = playerDataSlice.actions.editTagColor;
actions["SET_RANK"] = playerDataSlice.actions.setRank;
actions["ADD_CARD"] = playerDataSlice.actions.addCard;
actions["ADD_CARDS_LIST"] = playerDataSlice.actions.addCardsList;
actions["ADD_CARDS_KEYS"] = playerDataSlice.actions.addCardsKeys;
actions["ADD_CARDS_FROM_STORE"] = playerDataSlice.actions.addCardsFromStore;
actions["REMOVE_DECK_TAG"] = playerDataSlice.actions.removeDeckTag;
actions["ADD_DECK_TAG"] = playerDataSlice.actions.addDeckTag;
actions["SET_DECK_TAGS"] = playerDataSlice.actions.setDeckTags;
actions["SET_DECK"] = decksSlice.actions.setDeck;
actions["SET_MANY_DECKS"] = decksSlice.actions.setManyDecks;
actions["SET_MANY_STATIC_DECKS"] = decksSlice.actions.setManyStaticDecks;
actions["SET_ECONOMY"] = economySlice.actions.setEconomy;
actions["SET_MANY_ECONOMY"] = economySlice.actions.setManyEconomy;
actions["SET_DRAFT"] = draftsSlice.actions.setDraft;
actions["SET_MANY_DRAFT"] = draftsSlice.actions.setManyDrafts;
actions["SET_SEASONAL"] = seasonalSlice.actions.setSeasonal;
actions["SET_MANY_SEASONAL"] = seasonalSlice.actions.setManySeasonal;
actions["SET_DECK_CHANGE"] = deckChangesSlice.actions.setChange;
actions["SET_MANY_DECK_CHANGES"] = deckChangesSlice.actions.setManyChangees;

export default actions;
